services:
  mongo_1_single:
    image: mongo:8.0
    container_name: mongodb1_single
    hostname: mongodb1_single
    mem_limit: 400m
    volumes:
      - ./Docker_single/init:/docker-entrypoint-initdb.d
    networks:
      infrastructure:
        aliases:
          - mongodb1_single
    tmpfs:
      - /data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
      - MONGO_INITDB_DATABASE=facility_rental
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27017", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis
    hostname: redis
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data
    networks:
      infrastructure:
        aliases:
          - redis
    healthcheck:
      test: [ "CMD", "redis-cli", "PING" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: kacpermaziarz/facility_rental:0.0.1
    container_name: backend
    hostname: backend
    networks:
      infrastructure:
        aliases:
          - backend
    depends_on:
      - mongo_1_single
      - redis

  nginx:
    image: kacpermaziarz/facility_rental_nginx:0.0.1
    container_name: nginx
    mem_limit: 128m
    ports:
      - "20217:80"
    hostname: nginx
    depends_on:
        - backend
    restart: unless-stopped
    networks:
      - infrastructure



volumes:
  redis_data:

networks:
  infrastructure: