services:
  mongo_1_single:
    image: mongo:8.0
    mem_limit: 400m
    volumes:
      - ./Docker_single/init:/docker-entrypoint-initdb.d
    networks:
      - infrastructure
    tmpfs:
      - /data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
      - MONGO_INITDB_DATABASE=facility_rental
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27017", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data
    networks:
      - infrastructure
    healthcheck:
      test: [ "CMD", "redis-cli", "PING" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: kacpermaziarz/facility_rental:0.0.1
    mem_limit: 512m
    networks:
      - infrastructure
    depends_on:
      - mongo_1_single
      - redis
    environment:
       - JAVA_TOOL_OPTIONS:-XX:MaxRAMPercentage=60.0

  nginx:
    image: kacpermaziarz/facility_rental_nginx:0.0.1
    mem_limit: 128m
    ports:
      - "20217:80"
    hostname: nginx
    networks:
      - infrastructure



volumes:
    redis_data:

networks:
  infrastructure: